version: '3'
services:
  ukc-ep:
    image: "unboundukc/ukc-server:${UKC_VERSION:-latest}"
    container_name: ukc-ep
    restart: always
    ports:
     - "443:8443"
    command: ["ep", "ukc-partner", "ukc-aux"] 
    hostname: ukc-ep
    env_file:
      settings.env
  ukc-partner:
    image: "unboundukc/ukc-server:${UKC_VERSION:-latest}"
    container_name: ukc-partner
    restart: always
    command: ["partner", "ukc-ep", "ukc-aux"]
    hostname: ukc-partner
    depends_on:
      - "ukc-ep"
  ukc-aux:
    image: "unboundukc/ukc-server:${UKC_VERSION:-latest}"
    container_name: ukc-aux
    restart: always
    command: ["aux", "ukc-ep", "ukc-partner"]
    hostname: ukc-aux
    depends_on:
      - "ukc-ep"
      - "ukc-partner"